data_dir: "/mnt/s/Korea"
output_dir: "/mnt/u/interim_results"
git_dir: "/home/isong/GitHub/histmap-ko"

files:
  sites_history: "data/sites/sites_history_cleaning_20250311.xlsx"
  measurements: "airquality/outdoor/sites_airkorea_2010_2023_spt_yd.parquet"
  dem: "elevation/kngii_2022_merged_res30d.tif"
  dsm: "elevation/copernicus_korea_30m.tif"
  mtpi: "elevation/kngii_90m_mtpi.tif"
  watersheds: "watersheds/data/watershed-korea.gpkg"
  emissions: "emission/data/emission_location.gpkg"
  weather: "weather/data/asos_2010_2023.parquet"
  weather_sites: "weather/data/asos_sites.xlsx"

grid:
  resolution: 250

landuse_dir: "landuse/glc_fcs30d"
road_dir: "transportation/nodelink/data"

years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
